### ISSUE TITLE
Typo in resolv.conf configuration

### ISSUE THREAD

**Issue by waweber** [ansible-lockdown/RHEL8-STIG#14]
Check out fix-cat2.yml on line 1412 in v2.0.1:
```
      - name: "MEDIUM | RHEL-08-010680 | PATCH | For RHEL 8 systems using Domain Name Servers (DNS) resolution, at least two name servers must be configured. | Set resolv.conf if dns is set in nsswitch.conf"
        lineinfile:
            dest: /etc/resolv.conf
            regexp: '^nameserver'
            line: namserver "{{ item }}"
            insertafter: '^search'
        with_items:
            - "{{ rhel8stig_dns_servers }}"
        when:
            - rhel_08_010680_networkmanager_check != '# Generated by NetworkManager'
            - rhel_08_010680_nameserver_count.stdout|int < 2
```

This outputs `namserver "8.8.4.4"` etc., which has both nameserver misspelled and also the address cannot be in quotes, I assume `line: "nameserver {{item }}"` is the correct line. Incidentally, the README.md lists the default servers as 9.9.9.9 and 149.112.112.112 when they are actually the google 8.8.8.8 and 8.8.4.4. Also, the ansible `loop` statement in the `lineinfile` module results in the DNS servers being inserted in reverse order (the secondary server ends up first)

Ansible 2.10.9
