### ISSUE TITLE
fstype in fix-cat2.yml set to static value "xfs" on mount tasks

### ISSUE THREAD

**Issue by whitehat237** [ansible-lockdown/RHEL8-STIG#151]
For RHEL-08-040123, RHEL-08-040124, and RHEL-08-040125 tasks in fix-cat2.yml:

xfs is used as as the static value for the fstype parameter in tasks using the mount module instead of using the queried fstype value for the respective file system. The queried value is available to use and is already used in other tasks in fix-cat2.yml. I.E. "{{ home_mount.fstype }}"

The following mounts are affected:

- /tmp
- /var/log
-  /var/log/audit 
- /var/tmp

Using the queried fstype value instead of "xfs" as a hard coded static value, prevents a mount error and resulting dracut emergency shell when rebooting due to bad or incorrect fstype set in fstab, when xfs is not used as the actual file system for these mounts. For example, when using ext4.

**Expected Behavior**
Mount tasks for these file system mounts in tasks/fix-cat2.yml use the JSON queried value for fstype for each particular mount.

```yaml
     - name: |
            "MEDIUM | RHEL-08-040123 | PATCH | RHEL 8 must mount /tmp with the nodev option."
            "MEDIUM | RHEL-08-040124 | PATCH | RHEL 8 must mount /tmp with the nosuid option."
            "MEDIUM | RHEL-08-040125 | PATCH | RHEL 8 must mount /tmp with the noexec option."
        mount:
            path: /tmp
            state: mounted
            src: "{{ tmp_mount.device }}"
            fstype: "{{ tmp_mount.fstype }}"
            opts: "defaults{{ rhel_08_040123 | ternary (',nodev', '') }}{{ rhel_08_040124 | ternary (',nosuid', '') }}{{ rhel_08_040125 | ternary (',noexec', '') }}"
        vars:
            tmp_mount: "{{ ansible_mounts | json_query('[?mount == `/tmp`] | [0]') }}"
        when: rhel8stig_040123_dev_status.stdout | length > 0
  when:
      - rhel_08_040123 or
        rhel_08_040124 or
        rhel_08_040125
  tags:
      - CAT2
      - RHEL-08-040123
      - RHEL-08-040124
      - RHEL-08-04125
      - CCI-001764
      - SRG-OS-000368-GPOS-00154
      - SV-230511r627750_rule
      - SV-230512r627750_rule
      - SV-230513r627750_rule
      - V-230511
      - V-230512
      - V-230513
      - mounts
```

**Actual Behavior**
Mount tasks in fix-cat2.yml use static value "xfs" for the mounts mentioned above.

**Control(s) Affected**
RHEL-08-040123
RHEL-08-040124
RHEL-08-040125

**Environment (please complete the following information):**
 - Ansible Version:  >= 2.9.27
 - Host Python Version: Python 3.6.8
 - Ansible Server Python Version: 3.6.8

**Possible Solution**
Submitted [pull request](https://github.com/ansible-lockdown/RHEL8-STIG/pull/150#pullrequestreview-1216152938) and commit to use fstype value from JSON query.
