### ISSUE TITLE
Oracle Linux Distribution not identified correctly

### ISSUE THREAD

**Issue by BillSkiCO** [ansible-lockdown/RHEL8-STIG#239]
**Environment**
Project Version: `latest`
Ansible Version: `latest`
OS: `Oracle Linux 8.8`

Identified in the [prelim task](https://github.com/ansible-lockdown/RHEL8-STIG/blob/f845492af16e128fe04d211426b2bcb4b82dc5eb/tasks/prelim.yml#L389C26-L389C26)
- `ansible_distribution` variable for Oracle Linux is `OracleLinux` (no space). See `ansible/lib/ansible/module_utils/facts/system/distribution.py` [ODIST_LIST](https://github.com/ansible/ansible/blob/v2.16.0/lib/ansible/module_utils/facts/system/distribution.py#L56)
- prelim task is checking for `Oracle Linux` (with a space in distribution name)
```
      - name: "PRELIM | set fact if UEFI boot | Oracle Linux"
        ansible.builtin.set_fact:
            rhel8stig_bootloader_path: /boot/efi/EFI/redhat
            rhel8stig_legacy_boot: false
        when:
            - rhel8_efi_boot.stat.exists
            - ansible_distribution == 'Oracle Linux'    # <-- Here
```

This causes a downstream failure of the [`make grub2 config` handler](https://github.com/ansible-lockdown/RHEL8-STIG/blob/f845492af16e128fe04d211426b2bcb4b82dc5eb/handlers/main.yml#L56) as the `rhel8stig_bootloader_path` for Oracle Linux is interpreted as `/boot/efi/EFI/oraclelinux/` instead of `/boot/efi/EFI/redhat` which causes the `make grub2 config` to fail.
```
- name: make grub2 config
  ansible.builtin.shell: /usr/sbin/grub2-mkconfig --output={{ rhel8stig_bootloader_path }}/grub.cfg
  when:
      - rhel8stig_grub2_user_cfg.stat.exists
      - not rhel8stig_skip_for_travis
      - not system_is_container
```

Error Observed:
```
FAILED! => {"changed": true, "cmd": "/usr/sbin/grub2-mkconfig --output=/boot/efi/EFI/oraclelinux/grub.cfg", 
"delta": "0:00:20.741084", "end": "2023-11-29 08:32:42.667555",
"msg": "non-zero return code", "rc": 1, "start": "2023-11-29 08:32:21.926471",
"stderr": "/usr/sbin/grub2-mkconfig: line 274: /boot/efi/EFI/oraclelinux/grub.cfg.new: No such file or directory",
"stderr_lines": ["/usr/sbin/grub2-mkconfig: line 274: /boot/efi/EFI/oraclelinux/grub.cfg.new: No such file or directory"],
"stdout": "", "stdout_lines": []}
```

**Proposed fix**
Change `ansible_distribuition` check to `OracleLinux` in prelim.yml
```
      - name: "PRELIM | set fact if UEFI boot | Oracle Linux"
        ansible.builtin.set_fact:
            rhel8stig_bootloader_path: /boot/efi/EFI/redhat
            rhel8stig_legacy_boot: false
        when:
            - rhel8_efi_boot.stat.exists
            - ansible_distribution == 'OracleLinux'
```
