### ISSUE TITLE
RHEL_08_040321 does not consider rhel8stig_gui variable, and, sets system to use multi-user.target even when a gui is used. 

### ISSUE THREAD

**Issue by whitehat237** [ansible-lockdown/RHEL8-STIG#243]
**Describe the Issue**
In tasks/fix-cat2.yml, the following task, 
"MEDIUM | RHEL-08-040321 | PATCH | The graphical display manager must not be the default target on RHEL 8 unless approved." at line # 7404

Does not include a when statment to evaluate rhel8stig_gui variable
The resulting behavior is that systems with a graphical desktop installed, are set to use multi-user.target

**Expected Behavior**
Systems that are using a graphical desktop, where rhel8stig_gui is set to true, are not set to use multi-user.target by the task in tasks/fix-cat2.yml

**Actual Behavior**
The task at line 7404 in tasks/fix-cat2.yml sets the system to use multi-user.target regardless of whether rhel8stig_gui is set to true or not.  rhel8stig_gui is not considered by the task in the when clause.

**Control(s) Affected**
RHEL_08_040321

**Environment (please complete the following information):**

- branch being used: devel
- Ansible Version: 2.13.x
- Host Python Version: 3.6.8 (platform python)
- Ansible Server Python Version: N/A
- Additional Details: none

**Additional Notes**

**Possible Solution**
See commit and [pull request](https://github.com/ansible-lockdown/RHEL8-STIG/pull/244) which modifies the task to include rhel8stig_gui in the when statement:

```yaml
- name: "MEDIUM | RHEL-08-040321 | PATCH | The graphical display manager must not be the default target on RHEL 8 unless approved."
  ansible.builtin.file:
      src: /usr/lib/systemd/system/multi-user.target
      dest: /etc/systemd/system/default.target
      state: link
  when:
      - rhel_08_040321
      - not rhel8stig_gui
  tags:
      - RHEL-08-040321
      - CAT2
      - CCI-000366
      - SRG-OS-000480-GPOS-00227
      - SV-251718r809378_rule
      - V-251718
      - systemctl
```

**Comment by whitehat237** [comment]
We've had some internal discussion about this and I wanted to get the community's input.  Is the thought process here that others have a use case where the graphical desktop should be installed but the system should boot to multi-user.target, and not come up in graphical target?   The requirement being that one should have to do startx or similar to initialize the graphical environment when required.  If so, I can close the issue and the PR.  
Should rhel8stig_gui control whether or not V-251718 is implemented?

In our use case this makes more sense because our build process for newly provisioned systems configures the default to what it should be, and RHEL8-STIG shouldn't and doesn't need to control the default systemd target.  I.E. For development workstation systems, the default target is graphical.target, and for servers it's multi-user.target and we have different provisioning processes for the different platform types.

Our approach has been to use a pre-task  at the play level before calling the RHEL8-STIG role to determine GUI state and toggle rhel8stig_gui accordingly, based on whether or not the gdm package is installed.

```yaml
- name: Get installed package facts
  ansible.builtin.package_facts:

- name: set fact gui_state
  ansible.builtin.set_fact:
    gui_state: true
  when: "'gdm' in ansible_facts.packages"

- name: Import mindpoint group role RHEL8-STIG
  ansible.builtin.import_role:
    name: RHEL8-STIG
  vars:
    rhel8stig_gui: "{{ gui_state | default(false) }}"
```

We could add an additional task to our pre_tasks to also toggle rhel_08_040321.

```yaml

- name: Ensure rhel_08_040321 var is properly set based on GUI status
  ansible.builtin.set_fact:
    rhel_08_040321: "{{ gui_state }}"
```

Another approach to handle this could be to see if graphical.target is active and then set rhel_08_040321 accordingly.  Perhaps this is a better approach?

```yaml
- name: Check if graphical.target is active
  ansible.builtin.command: "/bin/systemctl is-active graphical.target"
  register: graphical_target_state
  changed_when: false

- name: Ensure rhel_08_040321 is set based on graphical target state
  ansible.builtin.set_fact:
      rhel_08_040321: true
  when: "'active' in graphical_target_state.stdout"
```

Or based on the configured default systemd target.  

```yaml
- name: Check if graphical.target is active
  ansible.builtin.command: "/bin/systemctl get-default"
  register: default_target
  changed_when: false

- name: Ensure rhel_08_040321 is set based on graphical target state
  ansible.builtin.set_fact:
      rhel_08_040321: true
  when: "'multi-user.target' in default_target.stdout"
```

Again, the idea with both of these approaches is that the box is configured per the organizational requirements before running the RHEL8-STIG role.

The [STIG control](https://www.stigviewer.com/stig/red_hat_enterprise_linux_8/2021-12-03/finding/V-251718) states:
"Document the requirement for a graphical user interface with the ISSO"

We assume that the documentation is per system, and should not globally apply to all systems.

Thoughts?
