### ISSUE TITLE
Script overwriting new mount options

### ISSUE THREAD

**Issue by dcarlojr** [ansible-lockdown/RHEL8-STIG#30]
Numerous mount option tasks are overwriting changes made by previous tasks because they are getting mount options from 'ansible_mounts' which is only collected at the beginning of the playbook run.

For example, **RHEL-08-010570** in fix-cat2 adds 'nosuid' to the mount options which is derived from ansible_mounts:
```
- name: "MEDIUM | RHEL-08-010570 | PATCH | RHEL 8 must prevent files with the setuid and setgid bit set from being executed on file systems that contain user home directories."
  mount:
      path: /home
      state: mounted
      src: "{{ home_mount.device }}"
      fstype: "{{ home_mount.fstype }}"
      opts: "{{ home_mount.options }},nosuid"
  when:
      - rhel_08_010570
      - ansible_mounts | selectattr('mount', 'match', '^/home$') | list | length != 0
      - "'nosuid' not in home_mount.options"
  vars:
      home_mount: "{{ ansible_mounts | json_query('[?mount == `/home`] | [0]') }}"
  tags:
      - RHEL-08-010570
      - mounts
      - home
```
At this point, the ansible_mount information is effectively stale as it relates to /etc/fstab.  Then **RHEL-08-010590** comes along and wipes out all of **RHEL-08-010570**'s hard work:
```
- name: "MEDIUM | RHEL-08-010590 | PATCH | RHEL 8 must prevent code from being executed on file systems that contain user home directories."
  mount:
      path: /home
      state: mounted
      src: "{{ home_mount.device }}"
      fstype: "{{ home_mount.fstype }}"
      opts: "{{ home_mount.options }},noexec"
  when:
      - rhel_08_010590
      - ansible_mounts | selectattr('mount', 'match', '^/home$') | list | length != 0
      - "'noexec' not in home_mount.options"
  vars:
      home_mount: "{{ ansible_mounts | json_query('[?mount == `/home`] | [0]') }}"
  tags:
      - RHEL-08-010590
      - mounts
      - home
```

Doing a remount won't help b/c the ansible facts are already collected.

Is this an ansible bug?
Can you recollect the ansible_mounts facts after a changed task?
