### ISSUE TITLE
Hosts are not configurable

### ISSUE THREAD

**Issue by ccravens** [ansible-lockdown/RHEL8-STIG#305]
## Feature Request or Enhancement

- Feature []
- Enhancement [X]

**Summary of Request**
In `site.yml`, hosts is not configurable and is hard-coded to all

```yaml
- name: Run RHEL8 CIS hardening
  hosts: all
  become: true

  roles:

      - role: "{{ playbook_dir }}"
```

**Describe Alternatives You've Considered**

**Suggested Code**
Submitting PR that adds a `hosts` variable to defaults, defaulted to `all` and uses the variable in the `site.yml` file.
