### ISSUE TITLE
Why is RHEL-08-020012 not being hardened or audited if the RedHat OS is at release 8.10?

### ISSUE THREAD

**Issue by hectoralicea** [ansible-lockdown/RHEL8-STIG#343]
**Have you checked [ReadtheDocs](https://ansible-lockdown.readthedocs.io/en/latest/)?:** Yes

**Question**
Why is [RHEL-08-020012](https://github.com/ansible-lockdown/RHEL8-STIG/blob/130f7fed1fcd2006048cd97e3e870a55369af2e0/tasks/fix-cat2.yml#L2780) not being hardened or audited if the RedHat OS is at release 8.10? 
```
- name: "MEDIUM | RHEL-08-020012 | PATCH | RHEL 8 must automatically lock an account when three unsuccessful logon attempts occur during a 15-minute time period."
  block:
      ... < left out code >
  when:
      - rhel_08_020012
      - ansible_distribution_version is version('8.1', '<=')
```
**Environment (please complete the following information):**

- Ansible Version: 4.3.0
- Host Python Version: 3.6.8
- Ansible Server Python Version: 3.6.8
- Additional Details:  RHEL 8.10
```
# cat /etc/os-release 
NAME="Red Hat Enterprise Linux"
VERSION="8.10 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.10"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.10 (Ootpa)"
```
