### ISSUE TITLE
RHEL-08-010400 - lineinfile task with state:present fails due to missing line: entry

### ISSUE THREAD

**Issue by cjakesmith** [ansible-lockdown/RHEL8-STIG#59]
RHEL-08-010400 - fix-cat2.yml line 897
Task as defined:

```
- name: "MEDIUM | RHEL-08-010400 | PATCH | RHEL 8 must implement certificate status checking for multifactor authentication."
  lineinfile:
      path: '{{ rhel8stig_sssd_conf }}'
      regexp: '^certificate_verification = {{ item.regexp }}'
      state: "{{ item.state }}"
  with_items:
      - { regexp: 'no_ocsp, no_verification', state: absent }
      - { regexp: 'no_ocsp', state: absent }
      - { regexp: 'no_verification', state: absent }
      - { regexp: 'ocsp_dgst=sha1', state: present }
  notify: restart sssd
  when:
      - rhel8stig_sssd_conf_present.stat.exists
      - rhel_08_010400
  tags:
      - RHEL-08-010400
      - CAT2
      - CCI-001948
      - SRG-OS-000375-GPOS-00160
      - SV-230274r627750_rule
      - V-230274
      - multifactor
```

Expected Behavior
Task should complete successfully

Actual Behavior
Task fails with error:
"msg": "line is required with state=present"

Control(s) Affected
fix-cat2.yml

Environment:
 - Ansible Version: 2.9
 - Host Python Version: 3.6.8
 - Ansible Server Python Version: 3.6.8
 - Additional Details:

Additional Notes
This role was ran from Ansible Tower - version: 3.8.2

Possible Solution:
Corrected task:
```
- name: "MEDIUM | RHEL-08-010400 | PATCH | RHEL 8 must implement certificate status checking for multifactor authentication."
  lineinfile:
      path: '{{ rhel8stig_sssd_conf }}'
      regexp: '^certificate_verification = {{ item.regexp }}'
      state: "{{ item.state }}"
      line: "{{ item.line | default(omit) }}"
  with_items:
      - { regexp: 'no_ocsp, no_verification', state: absent }
      - { regexp: 'no_ocsp', state: absent }
      - { regexp: 'no_verification', state: absent }
      - { regexp: 'ocsp_dgst=sha1', state: present, line: 'certificate_verification = ocsp_dgst=sha1' }
  notify: restart sssd
  when:
      - rhel8stig_sssd_conf_present.stat.exists
      - rhel_08_010400
  tags:
      - RHEL-08-010400
      - CAT2
      - CCI-001948
      - SRG-OS-000375-GPOS-00160
      - SV-230274r627750_rule
      - V-230274
      - multifactor
```
