### ISSUE TITLE
RHEL-08-020027 failed

### ISSUE THREAD

**Issue by PrymalInstynct** [ansible-lockdown/RHEL8-STIG#87]
**Describe the Issue**
RHEL-08-020027 failed with no changed to defaults/main.yml

``` FAILED! => {"changed": true, "cmd": "semanage fcontext -m -t faillog_t -s system_u /var/log/faillock", "delta": "0:00:02.776896", "end": "2022-02-23 09:42:41.815114", "msg": "non-zero return code", "rc": 1, "start": "2022-02-23 09:42:39.038218", "stderr": "ValueError: File context for /var/log/faillock is not defined", "stderr_lines": ["ValueError: File context for /var/log/faillock is not defined"], "stdout": "", "stdout_lines": []}```

**Expected Behavior**
I expect the task to pass without errors

**Actual Behavior**
tasks fail

**Control(s) Affected**
RHEL-08-020027

**Environment (please complete the following information):**
 - Ansible Version: 2.12.2
 - Host Python Version: Python 3.6.8
 - Ansible Server Python Version: Python 3.8.10
 - Additional Details:

**Additional Notes**
Anything additional goes here

**Possible Solution**
The tasks for this STIG seem a bit complicated I have tested the following and it worked
The directory gets created with the correct context and then the fcontext gets added so the change is permanent when running restorecon

```yaml
      - name: Part 1
        file:
            path: "{{ rhel8stig_pam_faillock.dir }}"
            owner: root
            group: root
            mode: '0700'
            state: directory
            recurse: yes
            setype: faillog_t

      - name: Part 2
        sefcontext:
            target: "{{ rhel8stig_pam_faillock.dir }}"
            ftype: d
            setype: faillog_t
            state: present
```
