### ISSUE TITLE
RHEL-08-04017 not applying on RHEL8 Workstation

### ISSUE THREAD

**Issue by JosephHoffman** [ansible-lockdown/RHEL8-STIG#88]
**Describe the Issue**
RHEL-08-04017 not applying on RHEL8 Workstation by not creating the `/etc/dconf/db/local.d/00-disable-CAD` file

**Expected Behavior**
The Role should create the following path/file: `/etc/dconf/db/local.d/00-disable-CAD` and populate with the following:
```
[org/gnome/settings-daemon/plugins/media-keys]
logout=''
```

**Actual Behavior**
tasks skips

**Control(s) Affected**
RHEL-08-04017

**Environment (please complete the following information):**
 - Ansible Version: 2.9.27
 - Host Python Version: 3.6.8
 - Ansible Server Python Version: N/A
 - Additional Details:

**Additional Notes**
The file this is configured in is `fix-cat1.yml` block line 384-422
```
- name: "HIGH | RHEL-08-040171 | PATCH | The x86 Ctrl-Alt-Delete key sequence in RHEL 8 must be disabled if a graphical user interface is installed."
  block:
      - name: "HIGH | RHEL-08-040171 | PATCH | The x86 Ctrl-Alt-Delete key sequence in RHEL 8 must be disabled if a graphical user interface is installed. | Check for setting existing"
        command: grep -s logout /etc/dconf/db/local.d/*
        changed_when: false
        failed_when: false
        register: rhel_08_040171_logout_settings_status

      - name: "HIGH | RHEL-08-040171 | PATCH | The x86 Ctrl-Alt-Delete key sequence in RHEL 8 must be disabled if a graphical user interface is installed. | Add if missing"
        lineinfile:
            path: /etc/dconf/db/local.d/00-disable-CAD
            regexp: "{{ item.regexp }}"
            line: "{{ item.line }}"
            insertafter: "{{ item.insertafter }}"
            create: yes
            owner: root
            group: root
            mode: 0644
        with_items:
            - { regexp: '^\[org/gnome/settings-daemon/plugins/media-keys\]', line: '[org/gnome/settings-daemon/plugins/media-keys]', insertafter: 'EOF' }
            - { regexp: 'logout=', line: "logout=''", insertafter: '\[org/gnome/settings-daemon/plugins/media-keys\]' }
        when: rhel_08_040171_logout_settings_status.stdout | length == 0

      - name: "HIGH | RHEL-08-040171 | PATCH | The x86 Ctrl-Alt-Delete key sequence in RHEL 8 must be disabled if a graphical user interface is installed. | Edit if exists"
        replace:
            path: "{{ rhel_08_040171_logout_settings_status.stdout }}"
            regexp: '^[L|l]ogout=.*'
            replace: "logout=''"
        when: rhel_08_040171_logout_settings_status.stdout | length > 0
  when:
      - rhel_08_040171
      - "'gnome-desktop' in ansible_facts.packages"
  tags:
      - RHEL-08-040171
      - CAT1
      - CCI-000366
      - SRG-OS-000480-GPOS-00227
      - SV-230530r646883_rule
      - V-230530
```

**Possible Solution**
RHEL8 does not seem to use gnome-desktop. In all my test cases it seems like gnome-desktop3 is the successor and installed when selecting RHEL8 Software selection: Workstation

Modification needed to: `fix-cat1.yml` on Line 415:

Currently:
`      - "'gnome-desktop' in ansible_facts.packages"`
Change to:
`      - "'gnome-desktop3' in ansible_facts.packages"`

Once I changed this locally the 00-disable-CAD file was created as to be expected.
